---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
        - 2f35fc4f8c28e3f0c1c6b139e3a16331
        - 9031d0c037ff0cb8cb3f8a6e1c4dc3c2
        - a817c97640284ca59b22d22f36a269cd

        - 4249a5ae65bc75eeb58b058691005cc4

        - a7be63e8544cd32d57a8d62c83ca5c57
  eslint:
    enabled: true
    checks:
      linebreak-style:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
